project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - "*.gif"
    - "*.py"
    - "VideosMetodosNumericos/*.mp4"

website:
  title: "Coleção Manim"
  description: "Animações matemáticas/didáticas de sistemas dinâmicos e conversores estáticos"
  site-url: https://raphateixeira.github.io/Manim/
  repo-url: https://github.com/raphateixeira/Manim

format:
  html:
    theme: [cosmo, TemaModelo.scss]
    lang: pt-BR
